apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cs3219-db
  namespace: cs3219
spec:
  serviceName: cs3219-db
  replicas: 2
  selector:
    matchLabels:
      app: cs3219-db
  template:
    metadata:
      labels:
        app: cs3219-db
    spec:
      containers:
        - name: cs3219-db
          image: nephelite/mariadb:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 3306
            name: cs3219-db
          env:
            - name: MYSQL_DATABASE
              value: cs3219
            - name: MYSQL_ROOT_PASSWORD
              value: password
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-persistent-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 50Mi